# Generated by Django 6.0.6 on 2026-07-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at']},
        ),
    ]
